torch_seed: 12345 # for reproducibility

rawdata_path: /sps/cms/gsaha/TauRegression/GNN_Input
df_name: GluGluHToTauTauSMdata_norm_11.h5
procdata_name: data_norm_11.pt
#inputs:
  #datapath: /pbs/home/g/gsaha/work/Regression/Input/DY_Cat_20231206_155537
#  datapath: /pbs/home/g/gsaha/work/TauRegression/Input
  #node_file: DY_nodes.parquet
  #target_file: DY_targets.parquet
  #global_file: DY_globals.parquet
#  dataframe: GluGluHToTauTauSMdata_norm.h5 

# date-time tag will be added after output
outputpath: /sps/cms/gsaha/TauRegression/GNN_Output/Output
#outputpath: /pbs/home/g/gsaha/work/TauRegression/Output/Output

train_frac: 0.80

hparamdict:
  nepochs: 100
  batchlen: 1024
  lr: 0.1
  momentum: 0.9
  betas: (0.9, 0.999)
  lr_stepsize: 5
  save_every: 5

# date-time tag will be added after trained models
modelpath: /sps/cms/gsaha/TauRegression/GNN_Output/TrainedModels
#modelpath: /pbs/home/g/gsaha/work/TauRegression/Output/TrainedModels

GPU: single # multi

train:
  cmd: True

val:
  cmd: True

test:
  cmd: False
  #final_model_path: /sps/cms/gsaha/TauRegression/GNN_Output/TrainedModels_20240327_135206/GNN_single_epoch99.pt
  final_model_path: /sps/cms/gsaha/TauRegression/GNN_Output/TrainedModels_20240401_015916/GNN_single_epoch99.pt
  #final_model_path: /pbs/home/g/gsaha/work/TauRegression/Output/TrainedModels_20231207_160456/GNN_DDP_epoch5.pt

evaluate:
  cmd: False


nodetypes:
  - tau
  - jet
# will be modified with tau_i and jet_i
nodefeats:
  - pt
  - eta
  - phi
  - mass
  - rawIsodR03
  #- rawMVAnewDM2017v2
  - leadTkPtOverTauPt
  - btagPNetB
  - rawPNetVSe
  - rawPNetVSjet
  - rawPNetVSmu
  - charge_1
  - charge_-1
  - decayModePNet_0
  - decayModePNet_1
  - decayModePNet_2
  - decayModePNet_10
  - decayModePNet_11
  - probDM0PNet
  - probDM1PNet
  - probDM2PNet
  - probDM10PNet
  - probDM11PNet
  - npf
  - ptfrac
  - pf_dphi_pt_frac
  - pf_deta_pt_frac


targettypes:
  - gentaunu
targetfeats:
  #- px_gentaunu_1
  #- py_gentaunu_1
  #- pz_gentaunu_1
  #- px_gentaunu_2
  #- py_gentaunu_2
  #- pz_gentaunu_2
  - phicp

globalfeats:
  - nJet
  #- nPV
  - HT
  - MT_total
  - pt_MET
  - phi_MET
  - covXX_MET
  - covXY_MET
  - covYY_MET
  - sumEt_MET
  - significance_MET


# model 1
# PNet follwed by GAT
node_block:
  pass