torch_seed: 12345 # for reproducibility

#rawdata_path: /sps/cms/gsaha/TauRegression/GNN_Input
rawdata_path: /sps/cms/gsaha/GluGluHToTauTauOutput

#df_name: GluGluHToTauTauSMdata_norm_11.h5
df_name: GluGluHToTauTauSMdata_ForTrain_Raw_11_simple_IC_20240411_124244.h5

#procdata_name: data_norm_11.pt
# Raw/Norm will automatially be added
procdata_name: data_ForTrain_11_simple_IC_20240411_124244.pt

# date-time tag will be added after output
outputpath: /sps/cms/gsaha/TauRegression/GNN_Output/Output

train_frac: 0.80

hparamdict:
  nepochs: 100
  batchlen: 1024
  lr: 0.1
  momentum: 0.9
  betas: (0.9, 0.999)
  lr_stepsize: 5
  save_every: 10

# date-time tag will be added after trained models
modelpath: /sps/cms/gsaha/TauRegression/GNN_Output/TrainedModels

# /sps/cms/gsaha/TauRegression/GNN_Output/TrainedModels_20240327_135206/GNN_single_epoch99.pt
# /pbs/home/g/gsaha/work/TauRegression/Output/TrainedModels_20231207_160456/GNN_DDP_epoch5.pt
# /sps/cms/gsaha/TauRegression/GNN_Output/TrainedModels_20240401_015916/GNN_single_epoch99.pt
final_model_path: /sps/cms/gsaha/TauRegression/GNN_Output/TrainedModels_20240412_092135/GNN_single_epoch70.pt

GPU: single # multi

plot:
  cmd: True

norm:
  cmd: True

train:
  cmd: True

val:
  cmd: True

test:
  cmd: True

evaluate:
  cmd: True

nodetypes:
  - tau
  - jet

nodefeats:
  numerical:
    - pt
    - eta
    - phi
    - mass
    - rawIsodR03
    #- rawMVAnewDM2017v2
    - leadTkPtOverTauPt
    - btagPNetB
    - rawPNetVSe
    - rawPNetVSjet
    - rawPNetVSmu
    - probDM0PNet
    - probDM1PNet
    - probDM2PNet
    - probDM10PNet
    - probDM11PNet
    - npf
    - ptfrac
    - pf_dphi_pt_frac
    - pf_deta_pt_frac
  categorical:
    - charge_1
    - charge_-1
    - decayModePNet_0
    - decayModePNet_1
    - decayModePNet_2
    - decayModePNet_10
    - decayModePNet_11

targettypes:
  - gentaunu
targetfeats:
  - px_gentaunu_1
  - py_gentaunu_1
  - pz_gentaunu_1
  - px_gentaunu_2
  - py_gentaunu_2
  - pz_gentaunu_2
  #- phicp
  - h1x
  - h1y
  - h1z
  - h2x
  - h2y
  - h2z


globalfeats:
  - nJet
  #- nPV
  - HT
  - MT_total
  - pt_MET
  - phi_MET
  - covXX_MET
  - covXY_MET
  - covYY_MET
  - sumEt_MET
  - significance_MET


# model 1
# PNet follwed by GAT
node_block:
  pass