torch_seed: 12345 # for reproducibility

df_name: GluGluHToTauTauSMdata.h5
inputs:
  #datapath: /pbs/home/g/gsaha/work/Regression/Input/DY_Cat_20231206_155537
  datapath: /pbs/home/g/gsaha/work/TauRegression/Input
  #node_file: DY_nodes.parquet
  #target_file: DY_targets.parquet
  #global_file: DY_globals.parquet
  dataframe: GluGluHToTauTauSMdata.h5 

outputpath: /pbs/home/g/gsaha/work/TauRegression/Output/Output

train_frac: 0.80

hparamdict:
  nepochs: 2
  batchlen: 2000
  lr: 0.01
  momentum: 0.9
  betas: (0.9, 0.999)
  lr_stepsize: 5
  save_every: 5

modelpath: /pbs/home/g/gsaha/work/TauRegression/Output/TrainedModels

GPU: single # multi

train:
  cmd: True

val:
  cmd: True

test:
  cmd: False
  final_model_path: /pbs/home/g/gsaha/work/TauRegression/Output/TrainedModels_20231207_160456/GNN_DDP_epoch5.pt

evaluate:
  cmd: False