## Config for GNN
indir:
  - /sps/cms/gsaha/GluGluHToTauTau_UncorrelatedDecay_CPodd_Filtered
  #- /sps/cms/gsaha/GluGluHToTauTau_M125_2016
  #- /sps/cms/gsaha/GluGluHToTauTau_M125_2017
  #- /sps/cms/gsaha/GluGluHToTauTau_M125_2018

outdir: /sps/cms/gsaha/GluGluHToTauTauOutput
  
isnorm: False

tau1dm: 1
tau2dm: 1

isForTrain: True

howtogetpizero: simple_IC