## Config for GNN

indir:
  #- /Volumes/WorkExtHDD/DY_NanoAOD_v10/DYJetsToLL_M-50-madgraphMLM
  #- /Volumes/WorkExtHDD/DY_NanoAOD_v10/DYJetsToLL_M-50-madgraphMLM_ext1
  - /sps/cms/gsaha/GluGluHToTauTau_M125

outdir: /sps/cms/gsaha/GluGluHToTauTauOutput

  
isnorm: True

tau1dm: 1
tau2dm: 1

isForTrain: False

howtogetpizero: simple_IC